name: Exploring Variables and Secrets

on:
  workflow_dispatch: 
#   schedule:
#     - cron: "*/1 * * * *"
# #    push


jobs:
    docker:
        env:
            CONTAINER_REGISTRY: docker.io
            IMAGE_TAG: github-actions-nginx
            
        runs-on: ubuntu-latest
        steps:
            - name: Docker Build
              run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_TAG
            - name: Docker Login
              run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
            - name: Docker Publish
              run: echo docker push $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_TAG
    deploy:
        needs: docker
        concurrency: 
          group: production-deployment
          cancel-in-progress: false
        env:
            CONTAINER_REGISTRY: docker.io
            DOCKER_USERNAME: dockerUsername
            IMAGE_TAG: github-actions-nginx
        runs-on: ubuntu-latest
        steps:
          - name: Docker
            timeout-minutes: 1
            run: |
              echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_TAG
              sleep 600s