name: workflow filters and activities

on:
    workflow_dispatch: 
    schedule:
        - cron: "*/59 * * * *"
    push:
    pull_request: 
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - run: echo this workflow/job/step is executed for event for event type - ${{ github.event_name }}